// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-YEt-qgyXy3tupJ9wpjMTQfrBfa93oc',
    appId: '1:168920436981:web:3041d7ffd443d2ed72b5bc',
    messagingSenderId: '168920436981',
    projectId: 'fysd-61d62',
    authDomain: 'fysd-61d62.firebaseapp.com',
    storageBucket: 'fysd-61d62.firebasestorage.app',
    measurementId: 'G-SHPVEYX2ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAM2AnyZITKsxKQDGPIPRh4bjy69DCVNw',
    appId: '1:168920436981:android:2f102814df8b94c572b5bc',
    messagingSenderId: '168920436981',
    projectId: 'fysd-61d62',
    storageBucket: 'fysd-61d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVt4ocKKm4hd9_o5cbTLY9tTwkOpHJjm0',
    appId: '1:168920436981:ios:668fde95480cc69372b5bc',
    messagingSenderId: '168920436981',
    projectId: 'fysd-61d62',
    storageBucket: 'fysd-61d62.firebasestorage.app',
    iosBundleId: 'com.example.fys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVt4ocKKm4hd9_o5cbTLY9tTwkOpHJjm0',
    appId: '1:168920436981:ios:668fde95480cc69372b5bc',
    messagingSenderId: '168920436981',
    projectId: 'fysd-61d62',
    storageBucket: 'fysd-61d62.firebasestorage.app',
    iosBundleId: 'com.example.fys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-YEt-qgyXy3tupJ9wpjMTQfrBfa93oc',
    appId: '1:168920436981:web:b8ae9e0d10075e4a72b5bc',
    messagingSenderId: '168920436981',
    projectId: 'fysd-61d62',
    authDomain: 'fysd-61d62.firebaseapp.com',
    storageBucket: 'fysd-61d62.firebasestorage.app',
    measurementId: 'G-8W9NX1QK6M',
  );
}
